import React from 'react';
import {
    Container,
    Typography,
    Box,
    Paper,
    Divider,
    List,
    ListItem,
    ListItemText
} from '@mui/material';

const TermsOfService = () => {
    return (
        <Container maxWidth="lg" sx={{ py: 8, mt: { xs: 5, sm: 6 } }}>
            <Paper elevation={3} sx={{ p: 4 }}>
                <Typography variant="h3" sx={{ mb: 4, fontFamily: "'Outfit', sans-serif", color: '#1a1a1a' }}>
                    Terms of Service
                </Typography>

                {/* Legal Notice */}
                <Box sx={{ mb: 4 }}>
                    <Typography variant="body1" paragraph sx={{ fontWeight: 'bold', bgcolor: '#f5f5f5', p: 2 }}>
                        THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
                    </Typography>
                </Box>

                {/* Agreement Notice */}
                <Box sx={{ mb: 4 }}>
                    <Typography variant="body1" paragraph>
                        By accessing, browsing, or using www.hotspotdigi.com or any other website, mobile version of the website (together "Website") or availing any products of HOTSPOT RETAIL PRIVATE LIMITED ("Company", "us", "we", "HOTSPOT DIGI"), you agree to be bound by these Terms and Conditions ("T&C").
                    </Typography>
                </Box>

                {/* Sections */}
                <Box sx={{ '& > *': { mb: 4 } }}>
                    {/* Products Section */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            1. PRODUCTS
                        </Typography>
                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Terms of Offer
                        </Typography>
                        <Typography variant="body1" paragraph>
                            The Website offers for sale certain products ("Products"). Products are for personal use only. You may not resell any Products unless agreed otherwise. We reserve the right to cancel or reduce quantities of any orders that may result in violation of our T&C.
                        </Typography>
                        
                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Product Information
                        </Typography>
                        <Typography variant="body1" paragraph>
                            We strive for accuracy in product descriptions, but we do not warrant that descriptions are accurate, complete, reliable, current, or error-free. Product pictures are indicative and may vary from actual Products.
                        </Typography>
                    </Box>

                    {/* Website Section */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            2. WEBSITE
                        </Typography>
                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Your Account
                        </Typography>
                        <Typography variant="body1" paragraph>
                            You may create and hold one user account. You are responsible for maintaining account confidentiality and all activities under your account. Each account is non-transferrable and may not be shared.
                        </Typography>

                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Payment Methods
                        </Typography>
                        <List>
                            <ListItem>
                                <ListItemText 
                                    primary="• Credit Cards, Debit Cards, Net Banking, Wallets, UPI, QR, PayPal"
                                    secondary="Payments through third-party gateways are contracts between you and the respective gateways"
                                />
                            </ListItem>
                            <ListItem>
                                <ListItemText primary="• Cash on Delivery" />
                            </ListItem>
                        </List>
                    </Box>

                    {/* Disclaimer Section */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            3. DISCLAIMER OF WARRANTIES
                        </Typography>
                        <Typography variant="body1" paragraph>
                            Your use of the Website and Products is at your sole risk. The Website and Products are offered "as is" and "as available" without warranties of any kind, whether express or implied.
                        </Typography>
                    </Box>

                    {/* Liability Section */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            4. LIMITATION OF LIABILITY
                        </Typography>
                        <Typography variant="body1" paragraph>
                            HOTSPOT DIGI will not be liable for any direct, indirect, incidental, special or consequential damages arising from the use of our Website or Products, including but not limited to loss of data, profits, or business interruption.
                        </Typography>
                    </Box>

                    {/* General Terms Section */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            5. GENERAL TERMS
                        </Typography>
                        <List>
                            <ListItem>
                                <ListItemText 
                                    primary="Force Majeure"
                                    secondary="We are not liable for any delay or failure due to circumstances beyond our reasonable control"
                                />
                            </ListItem>
                            <ListItem>
                                <ListItemText 
                                    primary="Governing Law"
                                    secondary="These terms are governed by the laws of India and the state of Delhi"
                                />
                            </ListItem>
                            <ListItem>
                                <ListItemText 
                                    primary="Termination"
                                    secondary="We reserve the right to terminate access to the Website for any violations of these terms"
                                />
                            </ListItem>
                        </List>
                    </Box>

                    {/* Contact Information */}
                    <Box>
                        <Typography variant="h5" sx={{ mb: 2, fontFamily: "'Outfit', sans-serif", color: '#ffb800' }}>
                            CONTACT US
                        </Typography>
                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Customer Service Desk:
                        </Typography>
                        <Typography variant="body1">Email: care@hotspotretail.in</Typography>
                        <Typography variant="body1">Phone: +91-70423 43404</Typography>
                        <Typography variant="body1" sx={{ mb: 2 }}>Hours: Monday-Saturday (9:00 AM to 6:00 PM)</Typography>

                        <Typography variant="h6" sx={{ mb: 1, fontFamily: "'Outfit', sans-serif" }}>
                            Grievance Officer:
                        </Typography>
                        <Typography variant="body1">Avnit</Typography>
                        <Typography variant="body1">Email: care@hotspotretail.in</Typography>
                        <Typography variant="body1">Hours: Monday-Friday (9:00 AM to 6:00 PM)</Typography>
                    </Box>
                </Box>

                <Divider sx={{ my: 4 }} />

                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                    Last updated: March 2025
                </Typography>
            </Paper>
        </Container>
    );
};

export default TermsOfService; 